import React from 'react';
import { CourseDocument, Section, HeaderFooterConfig, DEFAULT_HEADER_FOOTER_CONFIG } from '@/types';
import { LectureRenderer } from './LectureRenderer';
import { ExerciseRenderer } from './ExerciseRenderer';
import { ExamRenderer } from './ExamRenderer';
import { LessonRenderer } from './LessonRenderer';

interface DocumentPreviewProps {
    document: CourseDocument;
    showAnswers?: boolean;
    headerFooterConfig?: HeaderFooterConfig;
    isEditing?: boolean;
    onUpdateSection?: (sectionId: string, updatedSection: Section) => void;
    fontSizeLevel?: number; // 0=M, 1=L, 2=XL
}

export const DocumentPreview: React.FC<DocumentPreviewProps> = ({
    document,
    showAnswers = false,
    headerFooterConfig = DEFAULT_HEADER_FOOTER_CONFIG,
    isEditing = false,
    onUpdateSection,
    fontSizeLevel = 0
}) => {
    const { documentMetadata, sections } = document;
    const { header, footer } = headerFooterConfig;

    const renderSection = (section: Section, index: number) => {
        switch (section.type) {
            case 'lecture':
                return <LectureRenderer key={section.id || index} section={section} fontSizeLevel={fontSizeLevel} />;
            case 'lesson':
                return (
                    <LessonRenderer
                        key={section.id || index}
                        section={section}
                        isEditing={isEditing}
                        showAnswers={showAnswers}
                        onUpdate={(updatedSection) => onUpdateSection && onUpdateSection(section.id, updatedSection)}
                        fontSizeLevel={fontSizeLevel}
                    />
                );
            case 'exercise':
                return <ExerciseRenderer key={section.id || index} section={section} showAnswers={showAnswers} fontSizeLevel={fontSizeLevel} />;
            case 'exam':
                return <ExamRenderer key={section.id || index} section={section} showAnswers={showAnswers} fontSizeLevel={fontSizeLevel} />;
            default:
                return null;
        }
    };

    return (
        <div className="a4-paper bg-white text-black">
            {/* Header/Footer Removed as requested */}
            {/* 
            {header.enabled && (
                <header className="mb-12 border-b-2 border-black pb-8 no-print">
                   ...
                </header>
            )}
            */}

            {/* Print Header (repeats on each page) */}
            {/* 
            {header.enabled && (
                <div className="print-header-fixed hidden print:flex">
                   ...
                </div>
            )}
            */}

            {/* Print Footer (repeats on each page) */}
            {/* 
            {footer.enabled && (
                <div className="print-footer-fixed hidden print:flex">
                   ...
                </div>
            )}
            */}

            {/* Content */}
            <main>
                {sections.map(renderSection)}
            </main>

            {/* Screen Footer */}
            {footer.enabled && (
                <footer className="mt-12 pt-4 border-t border-gray-200 text-center text-xs text-gray-400 no-print">
                    <div className="flex justify-between items-center">
                        <span>{footer.leftText || ""}</span>
                        <span>{footer.centerText || "Generated by Teaching Docs Generator"}</span>
                        <span>{footer.rightText || ""}</span>
                    </div>
                </footer>
            )}

            {/* A4 Page Guides (Visual Check) - Only visible on screen, not print */}
            <div className="absolute top-0 left-0 w-full pointer-events-none z-50 no-print" style={{ height: '100%' }}>
                {/* 
                   A4 Height is 297mm. 
                   We will generate lines every 297mm to show where pages break.
                   We'll just create a repeated background pattern or a few absolute divs.
                   CSS repetition is easiest.
                */}
                <div
                    className="w-full h-full"
                    style={{
                        backgroundImage: 'linear-gradient(to bottom, transparent 296mm, red 297mm)',
                        backgroundSize: '100% 297mm',
                        opacity: 0.5
                    }}
                />
            </div>
        </div>
    );
};
