import React from 'react';
import { CourseDocument, Section, HeaderFooterConfig, DEFAULT_HEADER_FOOTER_CONFIG } from '@/types';
import { LectureRenderer } from './LectureRenderer';
import { ExerciseRenderer } from './ExerciseRenderer';
import { ExamRenderer } from './ExamRenderer';
import { LessonRenderer } from './LessonRenderer';

interface DocumentPreviewProps {
    document: CourseDocument;
    showAnswers?: boolean;
    headerFooterConfig?: HeaderFooterConfig;
    isEditing?: boolean;
    onUpdateSection?: (sectionId: string, updatedSection: Section) => void;
    fontSizeLevel?: number; // 0=M, 1=L, 2=XL
}

export const DocumentPreview: React.FC<DocumentPreviewProps> = ({
    document,
    showAnswers = false,
    headerFooterConfig = DEFAULT_HEADER_FOOTER_CONFIG,
    isEditing = false,
    onUpdateSection,
    fontSizeLevel = 0
}) => {
    const { documentMetadata, sections } = document;
    const { header, footer } = headerFooterConfig;

    const renderSection = (section: Section, index: number) => {
        switch (section.type) {
            case 'lecture':
                return <LectureRenderer key={`${section.id}-${index}`} section={section} fontSizeLevel={fontSizeLevel} />;
            case 'lesson':
                return (
                    <LessonRenderer
                        key={`${section.id}-${index}`}
                        section={section}
                        isEditing={isEditing}
                        showAnswers={showAnswers}
                        onUpdate={(updatedSection) => onUpdateSection && onUpdateSection(section.id, updatedSection)}
                        fontSizeLevel={fontSizeLevel}
                    />
                );
            case 'exercise':
                return <ExerciseRenderer key={`${section.id}-${index}`} section={section} showAnswers={showAnswers} fontSizeLevel={fontSizeLevel} />;
            case 'exam':
                return <ExamRenderer key={`${section.id}-${index}`} section={section} showAnswers={showAnswers} fontSizeLevel={fontSizeLevel} />;
            default:
                return null;
        }
    };

    return (
        <div className="min-h-screen bg-[#FBFBFA] py-12 flex justify-center selection:bg-[#cce9ff] selection:text-[#000000]">
            <div className="w-full max-w-[800px] bg-white px-12 py-16 shadow-sm sm:rounded-sm text-[#37352F] font-sans">
                {/* Header/Footer Removed as requested */}

                {/* Content */}
                <main className="space-y-10">
                    {sections.map(renderSection)}
                </main>

                {/* Screen Footer */}
                {footer.enabled && (
                    <footer className="mt-16 pt-8 border-t border-[#E1E1E0] text-center text-xs text-gray-400 no-print font-medium">
                        <div className="flex justify-between items-center opacity-60 hover:opacity-100 transition-opacity">
                            <span>{footer.leftText || ""}</span>
                            <span>{footer.centerText || "Generated by Teaching Docs Generator"}</span>
                            <span>{footer.rightText || ""}</span>
                        </div>
                    </footer>
                )}
            </div>
        </div>
    );
};
